### ISSUE TITLE
java.lang.NoSuchMethodError at StepperTouch.onTouchEvent(StepperTouch.kt:119) 'com.android.support:support-v4:26.0.0-beta1

### ISSUE THREAD

**Issue by AseevEIDev** [DanielMartinus/Stepper-Touch#11]
I use 'com.android.support:support-v4:26.0.0-beta1' in my application, and in dependencies i have an issure that I should use the smae version because of runtime errors.
But if I write code like this:
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.0-beta1'
            }
        }
    }
}
I have such error:

FATAL EXCEPTION: main
                                                                     Process: ru.mobiledev.badfit, PID: 28832
                                                                     java.lang.NoSuchMethodError: No direct method <init>(Landroid/view/View;Landroid/support/animation/DynamicAnimation$ViewProperty;F)V in class Landroid/support/animation/SpringAnimation; or its super classes (declaration of 'android.support.animation.SpringAnimation' appears in /data/app/ru.mobiledev.badfit-1/base.apk:classes14.dex)
                                                                         at nl.dionsegijn.steppertouch.StepperTouch.onTouchEvent(StepperTouch.kt:119)
                                                                         at android.view.View.dispatchTouchEvent(View.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                                         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java)
                                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java)
                                                                         at android.view.View.dispatchPointerEvent(View.java)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
                                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
                                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
                                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                         at android.os.MessageQueue.next(MessageQueue.java)
                                                                         at android.os.Looper.loop(Looper.java)
                                                                         at android.app.ActivityThread.main(ActivityThread.java)
07-14 18:00:35.669 28832-28832/ru.mobiledev.badfit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by AseevEIDev** [comment]
Just need to add in dependencies
 implementation 'com.android.support:support-dynamic-animation:26.0.0-beta1'

**Comment by DanielMartinus** [comment]
Good one, I'll update the library with the correct dependency.
