### ISSUE TITLE
crash on stepper touch - library version 0.6

### ISSUE THREAD

**Issue by atul-17** [DanielMartinus/Stepper-Touch#40]
java.lang.NoSuchMethodError: No direct method <init>(Landroid/view/View;Landroid/support/animation/DynamicAnimation$ViewProperty;F)V in class Landroid/support/animation/SpringAnimation; or its super classes (declaration of 'android.support.animation.SpringAnimation' appears in /data/app/example.atul.ballyhoohomescreenappchanges-2/split_lib_dependencies_apk.apk)
        at nl.dionsegijn.steppertouch.StepperTouch.onTouchEvent(StepperTouch.kt:151)
        at android.view.View.dispatchTouchEvent(View.java:9314)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)

**Comment by markusressel** [comment]
https://github.com/DanielMartinus/Stepper-Touch/issues/24
